### ISSUE TITLE
Keybinding  <Enter> from readme behaves differently

### ISSUE THREAD

**Issue by mcjvanschaik** [serenevoid/kiwi.nvim#15]
In the readme file the following key  bindings are mentioned.

    <Enter> -- Follow/Create wiki link.
    <Tab> -- Find next wiki link.
    T -- Toggle TODO list

Enter does not create a wiki link in Normal mode, this only works in Visual mode.

**Comment by serenevoid** [comment]
This was intentional. There is a slight change in kiwi.nvim and Vimwiki. 
On pressing <Enter>, Vimwiki creates a link first and then you have to press <Enter> again to open the new wiki file.
In kiwi.nvim, pressing <Enter> over a highlighted section creates a link and opens the new wiki file.
By allowing Enter key to work in normal mode would give rise to accidental wiki doc creations. So I had to make it work only in visual mode. This might be a personal preference. So if more people feel that its natural to have it the Vimwiki way, I'll consider having this.

**Comment by mcjvanschaik** [comment]
I think that the readme should be slightly changed in that case.

**Comment by mcjvanschaik** [comment]
I have created my very first pull request, I have made a helpfile and changed the README slightly to show the difference.
