### ISSUE TITLE
Plans to implement Journal?

### ISSUE THREAD

**Issue by dermorz** [serenevoid/kiwi.nvim#9]
Hey @serenevoid,

first of all: Great project. I found it looking for a neovim implementation of vimwiki.

Are there any plans to implement the journal feature? If not, do you think there is a way to script the Journal behavior and map it to key bindings?

Like:
- create a new page journal/yyyy-mm-dd.md
- create/update an index page with all journal entries

I think I need to refresh my Lua Fu and may contribute myself. 

Best,
Moritz

**Comment by serenevoid** [comment]
Hi @dermorz ,

Thanks for showing interest in my plugin. Happy to see more people using my simple plugin.

And to your question, I had both the features that you asked for in v0.2.0 .

I removed it when I moved to 0.3.0 to make the development of the wiki side more easier. Adding small improvements to the diary was a bit difficult because I had to consider the diary in each case. So I eventually removed it to make the plugin wiki specific. Also, almost no one wanted the journal feature to stay when I asked on Reddit since it wasn't used by many. There are better journal entry plugins available. So I made the first breaking change to the plugin by removing the journal feature.

But if you are interested in adding it, [here](https://github.com/serenevoid/kiwi.nvim/commit/5752c258d9ac32c161f0b1eda7f7d5e9d26e44cd) is the link to the commit where I removed all the journal features so that you can go through them and add it to your config if required.

Sincerely,
Void

**Comment by serenevoid** [comment]
I could explain my point of view on why I removed the journal feature.

I used to use the journal feature in the beginning too. But eventually I started to forget filling it some days and then totally stopped writing it at all.
So I thought writing a journal as a wiki would be the best option since we could write the date and create another doc as a wiki with this date as the name. Just a little manual work but it works well. I checked about this on [Reddit](https://www.reddit.com/r/neovim/comments/17hgz0g/kiwinvim_opinion_on_plugin_rewrite/) as well. The one comment I got said that its better to create the journal as an extension of this plugin if others required it. I felt that its the best option. So if someone wants to develop this, I am open to that as well. So for now I removed the journal and made space for easier upgrades on the wiki script.
